--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements. See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership. The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License. You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations
-- under the License.
--
-- name: D03_backtick_quoting_mysql_only
-- source: fineract-provider/src/main/java/org/apache/fineract/interoperation/service/InteropServiceImpl.java:158 (as of 8c187f9d1)
-- description: Reduced reproduction of the hard-coded backtick identifier
--   quoting in the interoperation KYC mapper. Backticks are the MySQL/MariaDB
--   identifier quote character; PostgreSQL uses double quotes and rejects a
--   backtick outright. Every other identifier in the same mapper goes through
--   DatabaseSpecificSQLGenerator.escape(), which emits the correct quote per
--   engine.
-- expect: mysql=pass postgres=fail
--
SELECT a.`address_line_1`, a.`address_line_2`
  FROM m_address a
 ORDER BY a.id
