--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements. See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership. The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License. You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations
-- under the License.
--
-- name: D07_only_full_group_by
-- source: audit control case for the GROUP BY strictness class
-- description: A projection of a column that is neither grouped nor
--   functionally dependent on the grouping key. PostgreSQL rejects it.
--   MariaDB 11.5's default sql_mode does not include ONLY_FULL_GROUP_BY, so it
--   accepts the statement and returns an arbitrary row's value per group. Any
--   query of this shape therefore migrates from "silently arbitrary" to "hard
--   failure"; the audit checked every GROUP BY in the raw-SQL call sites
--   against this rule.
-- expect: mysql=pass postgres=fail
--
SELECT je.account_id, je.entry_date, SUM(je.amount) AS total
  FROM acc_gl_journal_entry je
 GROUP BY je.account_id
