--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements. See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership. The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License. You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations
-- under the License.
--
-- name: D10_concat_null_semantics
-- source: 34 CONCAT() call sites in the raw-SQL scan, e.g.
--   fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/GSIMReadPlatformServiceImpl.java:243
--   and fineract-provider/src/main/java/org/apache/fineract/organisation/teller/service/TellerManagementReadPlatformServiceImpl.java:432,470,507
-- description: CONCAT() itself is portable, but its NULL handling is not.
--   MySQL/MariaDB return NULL if any argument is NULL; PostgreSQL's concat()
--   ignores NULL arguments and concatenates the rest. A projection built from a
--   nullable column therefore changes from NULL to a partially built string on
--   PostgreSQL. This is a display-value divergence, not a balance divergence,
--   but it silently changes API payloads.
-- expect: mysql=pass postgres=pass
-- known-divergence: yes
--
SELECT concat('(', CAST(NULL AS CHAR(10)), ') suffix') AS concat_with_null
