--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements. See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership. The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License. You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations
-- under the License.
--
-- name: D13_cast_char_truncation
-- source: fineract-core/src/main/java/org/apache/fineract/infrastructure/core/service/database/DatabaseSpecificSQLGenerator.java:163-169
-- description: PostgreSQL bare CHAR is char(1), so the old castChar output
--   truncated a multi-digit numeric identifier. The generator's old SQL is
--   reproduced directly here; both engines accept it but render differently.
-- expect: mysql=pass postgres=pass
-- known-divergence: yes
--
SELECT CAST(12 AS CHAR) AS code_id_text
