# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: fineract-aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${AWS_REGION}
      auth:
        jwt:
          serviceAccountRef:
            name: fineract-server

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fineract-tenants-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fineract-aws-secrets-manager
    kind: SecretStore
  target:
    name: fineract-tenants-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: ${FINERACT_DB_APP_SECRET_NAME}
        property: username
    - secretKey: password
      remoteRef:
        key: ${FINERACT_DB_APP_SECRET_NAME}
        property: password

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fineractmysql-root-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fineract-aws-secrets-manager
    kind: SecretStore
  target:
    name: fineractmysql-root-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: ${FINERACT_DB_ROOT_SECRET_NAME}
        property: password
